#!/usr/bin/env node
/* Reads scan_output/data/design_tokens.json (extracted CSS vars from the original
 * Laravel site) and writes src/styles/tokens.css as a Tailwind v4 @theme block.
 *
 * Tokens we care about: Tailwind palette colours + custom --primary / --primary-dark
 * + shadows + a few semantic surface colours we add on top.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PROJECT_ROOT = path.resolve(ROOT, '..');
const TOKENS_IN = path.join(PROJECT_ROOT, 'scan_output', 'data', 'design_tokens.json');
const TOKENS_OUT = path.join(ROOT, 'src', 'styles', 'tokens.css');

const raw = JSON.parse(readFileSync(TOKENS_IN, 'utf8'));
const css_vars =
  raw.css_color_variables ??
  raw.css_variables ??
  raw.css_vars ??
  raw.variables ??
  raw.tokens ??
  [];

const map = new Map();
for (const entry of css_vars) {
  if (entry && entry.name && entry.value && typeof entry.value === 'string') {
    // Skip noisy unset / "&#039;" garbage values.
    if (entry.value.includes('&#') || entry.value.trim() === '' || entry.value === '0 0 #0000') continue;
    map.set(entry.name, entry.value);
  }
}

// Keep only the variables we actually consume in the React UI.
const KEEP_PREFIXES = ['--color-', '--shadow-', '--drop-shadow-', '--radius-'];
const KEEP_EXACT = new Set(['--primary', '--primary-dark', '--font-primary']);

const kept = [...map.entries()]
  .filter(([n]) => KEEP_EXACT.has(n) || KEEP_PREFIXES.some((p) => n.startsWith(p)))
  .sort(([a], [b]) => a.localeCompare(b));

const PRIMARY = map.get('--primary') ?? '#10b981';
const PRIMARY_DARK = map.get('--primary-dark') ?? '#059669';

const semantic = [
  ['--color-app-bg', map.get('--color-slate-50') ?? 'oklch(0.984 0.003 247.858)'],
  ['--color-app-fg', map.get('--color-slate-900') ?? 'oklch(0.208 0.042 265.755)'],
  ['--color-sidebar', map.get('--color-slate-900') ?? 'oklch(0.279 0.041 260.031)'],
  ['--color-sidebar-fg', map.get('--color-slate-50') ?? 'oklch(0.968 0.007 247.896)'],
  ['--color-sidebar-hover', map.get('--color-slate-700') ?? 'oklch(0.372 0.044 257.287)'],
  ['--color-sidebar-section', 'oklch(0.704 0.04 256.788)'],
  ['--color-card', '#ffffff'],
  ['--color-border', map.get('--color-slate-200') ?? 'oklch(0.929 0.013 255.508)'],
  ['--color-muted', map.get('--color-slate-500') ?? 'oklch(0.554 0.046 257.417)'],
  // Brand primary — the source dump has `--primary` (no `--color-` prefix); the React
  // code references both, so we emit both spellings as aliases.
  ['--color-primary', PRIMARY],
  ['--color-primary-dark', PRIMARY_DARK],
  // Mid-stop shades that the source dump skipped (e.g., orange-400) but our
  // gradients reference. Interpolated visually between adjacent scan stops.
  ['--color-orange-400', map.get('--color-orange-400') ?? 'oklch(0.769 0.188 56)'],
  ['--color-teal-500', map.get('--color-teal-500') ?? 'oklch(0.704 0.135 183)'],
  ['--color-violet-600', map.get('--color-violet-600') ?? 'oklch(0.541 0.281 293.009)'],
  ['--color-yellow-500', map.get('--color-yellow-500') ?? 'oklch(0.795 0.184 86)'],
  ['--color-emerald-400', map.get('--color-emerald-400') ?? 'oklch(0.768 0.16 162.65)'],
  ['--color-rose-500', map.get('--color-rose-500') ?? 'oklch(0.645 0.246 16.439)'],
  ['--color-rose-600', map.get('--color-rose-600') ?? 'oklch(0.586 0.253 17.585)'],
  ['--color-yellow-600', map.get('--color-yellow-600') ?? 'oklch(0.681 0.162 75.834)'],
  // Card surface + elevation shadows used by every list/dashboard card. The
  // source dump's --shadow-sm / --shadow-md are close enough but we want a
  // stable semantic alias so we can tune the card look in one place.
  ['--shadow-card', '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.05)'],
  ['--shadow-elev', '0 10px 15px -3px rgb(0 0 0 / 0.10), 0 4px 6px -4px rgb(0 0 0 / 0.08)'],
  ['--radius-card', '0.75rem'],
  ['--radius-input', '0.5rem'],
  ['--font-sans', '"Tajawal", "Inter", system-ui, sans-serif'],
];

const lines = [
  '/* AUTO-GENERATED by scripts/generate-tokens.mjs.',
  ' * Source: scan_output/data/design_tokens.json',
  ' * Edit the source or the generator, not this file.',
  ' */',
  '@theme {',
  ...semantic.map(([n, v]) => `  ${n}: ${v};`),
  '',
  ...kept.map(([n, v]) => `  ${n}: ${v};`),
  '}',
  '',
];

mkdirSync(path.dirname(TOKENS_OUT), { recursive: true });
writeFileSync(TOKENS_OUT, lines.join('\n'), 'utf8');
console.log(`✓ tokens.css written (${kept.length} palette + ${semantic.length} semantic vars)`);
